name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Haetaan lähdekoodit reposta.
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Asennetaan Node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 3. Asennetaan projektin riippuvuudet.
      - name: Install dependencies
        run: npm install

      # 4. Buildataan projekti.
      - name: Build
        run: npm run build

      # 5. Julkaistaan Web App -palveluun.
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: lemon-clicker-demo-p71678ß
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISHED_LEMON_CLICKER }}
          package: ./dist